name: S3Deploy
on:
  push:
    branches: [ master, feature/add-s3-autodeploy-with-github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: env

    # # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    #     unzip awscliv2.zip
    #     sudo ./aws/install

    # # Deploy S3 files
    # - name: Deploy S3 files 
    #   run: aws s3 ls
