name: S3Deploy
on:
  push:
    branches: [ master, feature/*]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # Install AWS CLI used for S3 files deployment
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip > /dev/null 2>&1
        sudo ./aws/install > /dev/null 2>&1

    - name: Deploy app files to S3 hosting
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "eu-west-1"
      run: |
        set -x
        aws s3 cp src s3://perception.ninja --recursive